version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      spring-and-security:
        patterns:
          - "org.springframework*"
          - "org.owasp*"
          - "io.jsonwebtoken*"
